### ISSUE TITLE
Get rid of glsl-parser

### ISSUE THREAD

**Issue by dy** [stackgl/glsl-transpiler#23]
- _glsl-parser_ has at least 3 incompatibilities with OpenGL 440, which are unlikely to be fixed. I cannot fix them myself as the code style and structure and my brain are hardly compatible :(. Unlike the _glsl-tokenizer_.
- There are good modules for _glsl-tokenizer_ already, like glsl-preprocessor, glsl-variables etc, seek in stackgl org.
- _glsl-parser_ ignores some information in nodes, like types etc keywords so that we still have to retrieve that from tokens.
- _glsl-parser_ seems to have not the best nodes classification: binary operators are mixed with access nodes, which are also something separate. Declaration expressions are messy and by fact duplicate assignments, the logic of parsing them is mess.
- in sourcemaps we still gotta retrieve things from tokens, so tackling them from ast is difficulter than tokens.

**Comment by dfcreative** [comment]
In that case it is simpler to begin anew walk the path of glsl.js - just resurrect the grammar described in [section 9 of 440](https://www.opengl.org/registry/doc/GLSLangSpec.4.40.pdf) and process tokens separately

**Comment by dy** [comment]
Skipping for now, glsl-parser issues are fixed.
