### ISSUE TITLE
Not parsing mat * vec correctly

### ISSUE THREAD

**Issue by Pessimistress** [stackgl/glsl-transpiler#34]
`mat * vec` should return `vec` type:
https://en.wikibooks.org/wiki/GLSL_Programming/Vector_and_Matrix_Operations

This line makes the out type `mat`:
https://github.com/stackgl/glsl-transpiler/blob/master/lib/operators.js#L175

**Comment by dy** [comment]
Thanks, fixed. But for the matter it does not affect the result, since `vec` and `mat` are represented as arrays in js. Just wonder what was your use case for that.

**Comment by Pessimistress** [comment]
@dy Thank you! In my use case the compiler throws an error at an expression of type
`mat4 * vec4 + vec4`
As it thinks I'm adding a matrix to an vector.

**Comment by dy** [comment]
Ok. Published as 1.5.9
