### ISSUE TITLE
Option to compile WebGL1 shaders?

### ISSUE THREAD

**Issue by Pessimistress** [stackgl/glsl-transpiler#35]
In 1.5.10 the `{ version: '300 es' }` option was added:
https://github.com/stackgl/glsl-transpiler/blob/master/lib/parse.js#L17

And the compiler no longer works with WebGL1 shaders. Is it possible to expose this as an option?

**Comment by dy** [comment]
Sure. 1.7.0 has `version` option and uses `100 es` by default.
