### ISSUE TITLE
`out` qualifier is not working as intended.

### ISSUE THREAD

**Issue by 1chandu** [stackgl/glsl-transpiler#38]
When using glsl function with a `out` qualifier parameter, converted JS function doesn't support `out` functionality. In my case it is `vec4`, it takes an array and assigns a new values inside a function , which is not visible outside of the function.

Here is the use case :

shader source :
```
vec4 project_position_to_clipspace(
  vec3 position, vec2 position64xyLow, vec3 offset, out vec4 worldPosition
) {
  vec3 projectedPosition = project_position(position, position64xyLow);
  worldPosition = vec4(projectedPosition + offset, 1.0);
  return project_to_clipspace(worldPosition);
}
```

transpiled JS : 

```
function project_position_to_clipspace (position, position64xyLow, offset, worldPosition) {
	var projectedPosition = project_position_vec3_vec2(position, position64xyLow);
	worldPosition = [projectedPosition[0] + offset[0], projectedPosition[1] + offset[1], projectedPosition[2] + offset[2], 1];
	return project_to_clipspace(worldPosition);
};

```

how I want to use the it :

```
const worldPosition = [];
project_position_to_clipspace([-122.45, 37.78, 0], [0, 0], [0, 0, 0], worldPosition);
```

Given the out variable is updated inside the transpiled JS method, the caller can't get the value out. One possible way is to provide and object as input for each `out` variable, and inside JS function, set a calculated value as with `out` variables name as `key`, or any other way, so the caller can get the updated value.

**Comment by dy** [comment]
How would you suggest compiling the case

```js
void fn(out float x) { x = 1.;}
void main() {
  float a = 0.;
  a = fn(a) + a;
}
```

**Comment by Pessimistress** [comment]
Without too much interruption to how things work today:

Input:

```glsl
void fn(out float x) {
  x = 1.;
}
void main() {
  float a = 0.;
  a = fn(a) + a;
}
```

Output:

```js
var __return__;
var __out__;
function fn(x) {
  x = 1.0;
  __return__ = undefined;
  __out__ = [x];
  return __return__;
}
function main() {
  var a = 0.0;
  a = (fn(a), [a] = __out__, __return__) + a;
}
```

This would also work with nested cases, e.g. input: 

```glsl
float fn1(out float x) {
  x = 1.;
  return 3.;
}
float fn2(out float x) {
  x = 2.;
  return fn1(x);
}
void main() {
  float a = 0.;
  a = fn2(a) + a;
}
```

Output:

```js
var __return__;
var __out__;
function fn1(x) {
  x = 1.0;
  __return__ = 3.0;
  __out__ = [x];
  return __return__;
}
function fn2(x) {
  x = 2.0;
  __return__ = (fn1(x), [x] = __out__, __return__);
  __out__ = [x];
  return __return__;
}
function main() {
  var a = 0.0;
  a = (fn2(a), [a] = __out__, __return__) + a;
}
```

**Comment by Pessimistress** [comment]
@dy Any thoughts on this?

**Comment by dy** [comment]
@Pessimistress your variant is valid, it is just a bit difficult for me to implement now.
Do you depend on that in any way?

**Comment by Pessimistress** [comment]
I'm not blocked but I would love to get this fixed at some point. Can I help in any way?

**Comment by dy** [comment]
@Pessimistress you can make a PR or assign a bounty if that is of somewhat urgent matter. I can't switch here for the next week or a couple.
