### ISSUE TITLE
lib/stdlib/texture: UV coordinates range is exclusive

### ISSUE THREAD

**Issue by geoffreytools** [stackgl/glsl-transpiler#58]
Hi,

I noticed weird wrapping when testing code that is using a texture as input.

When I use `texture2D`, coordinates which are exactly `1` are treated as if they were `0`.

In `lib/stdlib.js` I can find `% 1` in the function bellow
```js
function texture (sampler, coord, bias) {
	var size = textureSize(sampler);
	var x = ((coord[0] % 1) * size[0])|0;
	var y = ((coord[1] % 1) * size[1])|0;
	var idx = y * 4 * size[0] + x * 4;
	if (sampler.data) {
		return sampler.data.slice(idx, idx + 4);
	}
	return sampler.slice(idx, idx + 4);
}
```
I think this is incorrect. There should be no wrapping if the coordinate does not overshoot `1`.

This also makes me think that there appears to be no support for wrapping mode.

**Comment by dy** [comment]
Thanks, fixed. Atm only CLAMP_TO_EDGE (default) texture wrap mode is supported.
