### ISSUE TITLE
Boolean negation/NOT prepends "null ", causing JS syntax error

### ISSUE THREAD

**Issue by willheslam** [stackgl/glsl-transpiler#61]
```javascript
import GLSL from "glsl-transpiler";

const glsl = new GLSL({ });

const result = glsl(`!foo;`);

result === '\nnull ! foo;'
```

`!` isn't included in the "examplary source, containing all possible tokens" inside test/api.js or test/fixture/*.glsl

Under lib/operators.js, boolean complement and negation have been commented out since
https://github.com/stackgl/glsl-transpiler/commit/d68a9edeeeb76d70e4980e22929f05f97fe19106
so it looks like this has been this way for a while.

Uncommenting out either of the operators causes the tests to fail with
```
~/glsl-transpiler$ npm test

> glsl-transpiler@3.0.0 test
> node test/index.js

undefined:3
out[0] = a[0] ! b[0]
              ^

SyntaxError: Unexpected token '!'
    at new Function (<anonymous>)
    at createOperations (file:///home/willheslam/glsl-transpiler/lib/stdlib.js:99:30)
```
My guess is this is because `!` and `~` are unary operators, not binary.

This gives a clue as to why `null` is being prepended - perhaps glsl-transpiler is treating the `!` token as though it's binary, and `null` is the missing first operand! Hopefully it's a straight forward fix because GLSL and JS are 1:1 here, at least syntactically.

`processOperation` in operators.js already seems to handle unary operators like `i++` and `-x` so hopefully it can also apply to `!` and `~`.

A workaround for now is just to negate manually, i.e. `foo ? false : true` or `foo == false`.

**Comment by dy** [comment]
Ok, thanks for the report @willheslam!
I've fixed the issue, not convinced it was the best way but it works.
Cheers
